links:
  - product: chrome
    url: https://bugs.chromium.org/p/chromium/issues/detail?id=767040
    results:
    - test: storage.https.html
      status: TIMEOUT
  - product: safari
    url: <insert url>
    results:
    - test: navigation.https.html
      status: FAIL
